package ww.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PF_ATHLETE.
 */
public class pf_athlete {

    private Long ID;
    private String athlete_ID;
    private Integer athlete_order;
    private String athlete_name;
    private String athlete_group;

    public pf_athlete() {
    }

    public pf_athlete(Long ID) {
        this.ID = ID;
    }

    public pf_athlete(Long ID, String athlete_ID, Integer athlete_order, String athlete_name, String athlete_group) {
        this.ID = ID;
        this.athlete_ID = athlete_ID;
        this.athlete_order = athlete_order;
        this.athlete_name = athlete_name;
        this.athlete_group = athlete_group;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getAthlete_ID() {
        return athlete_ID;
    }

    public void setAthlete_ID(String athlete_ID) {
        this.athlete_ID = athlete_ID;
    }

    public Integer getAthlete_order() {
        return athlete_order;
    }

    public void setAthlete_order(Integer athlete_order) {
        this.athlete_order = athlete_order;
    }

    public String getAthlete_name() {
        return athlete_name;
    }

    public void setAthlete_name(String athlete_name) {
        this.athlete_name = athlete_name;
    }

    public String getAthlete_group() {
        return athlete_group;
    }

    public void setAthlete_group(String athlete_group) {
        this.athlete_group = athlete_group;
    }

}
