package ww.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PF_FOUL.
 */
public class pf_foul {

    private Long foul_ID;
    private Long group_ID;
    private Long referee_ID;
    private String foul_athlete_ID;
    private String foul_time;
    private Integer foul_card;
    private Integer foul_type;
    private String foul_upload;
    private String foul_referee_name;
    private String foul_MAC;
    private String foul_description;

    public pf_foul() {
    }

    public pf_foul(Long foul_ID) {
        this.foul_ID = foul_ID;
    }

    public pf_foul(Long foul_ID, Long group_ID, Long referee_ID, String foul_athlete_ID, String foul_time, Integer foul_card, Integer foul_type, String foul_upload, String foul_referee_name, String foul_MAC, String foul_description) {
        this.foul_ID = foul_ID;
        this.group_ID = group_ID;
        this.referee_ID = referee_ID;
        this.foul_athlete_ID = foul_athlete_ID;
        this.foul_time = foul_time;
        this.foul_card = foul_card;
        this.foul_type = foul_type;
        this.foul_upload = foul_upload;
        this.foul_referee_name = foul_referee_name;
        this.foul_MAC = foul_MAC;
        this.foul_description = foul_description;
    }

    public Long getFoul_ID() {
        return foul_ID;
    }

    public void setFoul_ID(Long foul_ID) {
        this.foul_ID = foul_ID;
    }

    public Long getGroup_ID() {
        return group_ID;
    }

    public void setGroup_ID(Long group_ID) {
        this.group_ID = group_ID;
    }

    public Long getReferee_ID() {
        return referee_ID;
    }

    public void setReferee_ID(Long referee_ID) {
        this.referee_ID = referee_ID;
    }

    public String getFoul_athlete_ID() {
        return foul_athlete_ID;
    }

    public void setFoul_athlete_ID(String foul_athlete_ID) {
        this.foul_athlete_ID = foul_athlete_ID;
    }

    public String getFoul_time() {
        return foul_time;
    }

    public void setFoul_time(String foul_time) {
        this.foul_time = foul_time;
    }

    public Integer getFoul_card() {
        return foul_card;
    }

    public void setFoul_card(Integer foul_card) {
        this.foul_card = foul_card;
    }

    public Integer getFoul_type() {
        return foul_type;
    }

    public void setFoul_type(Integer foul_type) {
        this.foul_type = foul_type;
    }

    public String getFoul_upload() {
        return foul_upload;
    }

    public void setFoul_upload(String foul_upload) {
        this.foul_upload = foul_upload;
    }

    public String getFoul_referee_name() {
        return foul_referee_name;
    }

    public void setFoul_referee_name(String foul_referee_name) {
        this.foul_referee_name = foul_referee_name;
    }

    public String getFoul_MAC() {
        return foul_MAC;
    }

    public void setFoul_MAC(String foul_MAC) {
        this.foul_MAC = foul_MAC;
    }

    public String getFoul_description() {
        return foul_description;
    }

    public void setFoul_description(String foul_description) {
        this.foul_description = foul_description;
    }

}
