package ww.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PF_GROUP.
 */
public class pf_group {

    private Long group_ID;
    private String group_CHN_content;
    private String group_ENG_content;
    private String group_description;

    public pf_group() {
    }

    public pf_group(Long group_ID) {
        this.group_ID = group_ID;
    }

    public pf_group(Long group_ID, String group_CHN_content, String group_ENG_content, String group_description) {
        this.group_ID = group_ID;
        this.group_CHN_content = group_CHN_content;
        this.group_ENG_content = group_ENG_content;
        this.group_description = group_description;
    }

    public Long getGroup_ID() {
        return group_ID;
    }

    public void setGroup_ID(Long group_ID) {
        this.group_ID = group_ID;
    }

    public String getGroup_CHN_content() {
        return group_CHN_content;
    }

    public void setGroup_CHN_content(String group_CHN_content) {
        this.group_CHN_content = group_CHN_content;
    }

    public String getGroup_ENG_content() {
        return group_ENG_content;
    }

    public void setGroup_ENG_content(String group_ENG_content) {
        this.group_ENG_content = group_ENG_content;
    }

    public String getGroup_description() {
        return group_description;
    }

    public void setGroup_description(String group_description) {
        this.group_description = group_description;
    }

}
